Repository Zanit-Development/Zanit_FE, pull requests merged in 2023-10, with the labels that each got.

#118 feat : 검색
  src/components/tag/NewTag.tsx
  src/libs/interface/interfaceSearch.ts
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/search/Search.tsx
  src/pages/search/handleSubmit.ts
Labels: ✨ Feature, 🔨 Refactor

#120 add : useCoupon api연결
  src/components/common/selectBox/SelectBox.tsx
  src/components/modal/Modal.tsx
  src/components/useCoupon/ShowPopupButton.tsx
  src/components/useCoupon/UseCouponPopup.tsx
  src/libs/apis/useCoupon.ts
  src/libs/interface/interfaceUseCoupon.ts
  src/pages/myCoupon/UseCoupon.tsx
Labels: ✨ Feature, 📬 API

#121 feat : 어드민 바 정보 관리페이지
  src/components/admin/management/CocktailItem.tsx
  src/pages/admin/bar/ManageInfo.tsx
Labels: ✨ Feature

#123 fix: 로그인 오류 수정
  src/components/modal/useSignPage/PopupLogout.tsx
  src/layouts/adminLayout/AdminLayout.tsx
  src/layouts/adminLayout/AdminNav.tsx
  src/layouts/nav/Nav.tsx
  src/libs/apis/user.ts
  src/pages/admin/AdminSignIn.tsx
  src/pages/sign/SignIn.tsx
Labels: ✨ Feature, 🐞 BugFix

#124 Feature/bar detail
  @types/react-pinch-zoom-pan.d.ts
  package-lock.json
  package.json
  src/components/barDetail/ImgContainer.tsx
  src/components/barDetail/MainImage.tsx
  src/libs/apis/axios.ts
  src/pages/Temporary.tsx
  tsconfig.json
Labels: ✨ Feature, 📬 API

#127 feat : 바관리, 칵테일추가 팝업, 폴더 분리 등
  src/App.tsx
  src/components/admin/management/CocktailItem.tsx
  src/components/admin/management/cocktailItemOptions.ts
  src/components/barDetail/BarInfomation.tsx
  src/components/common/cocktail/Cocktail.tsx
  src/components/tag/SearchTag.tsx
  src/libs/interface/interfaceCocktail.ts
  src/pages/admin/bar/BarManagement.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
  src/pages/admin/order/ManageOrder.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor

#126 feat: 로그인 관련
  .vscode/settings.json
  src/components/sign/SignInForm.tsx
  src/libs/apis/user.ts
  src/pages/admin/AdminSignIn.tsx
  src/pages/sign/PasswordReset.tsx
  src/pages/sign/SignIn.tsx
Labels: ✨ Feature, 📬 API

#130 refactor : 칵테일검색 바이름검색으로 변경 및 칵테일 태그 recoUser에 맞춰서 변경
  src/pages/search/Search.tsx
  src/pages/search/handleSubmit.ts
Labels: 🔨 Refactor

#133 feat : 홈 화면에서 검색 혹은 태그 선택시 검색 페이지로 해당 값 가져오는 기능
  src/components/common/cocktail/Cocktail.tsx
  src/components/search/Category.tsx
  src/components/tag/SearchTag.tsx
  src/components/tag/TagList.tsx
  src/libs/interface/interfaceCommon.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/search/Search.tsx
  src/pages/search/handleSubmit.ts
  src/pages/search/options.ts
Labels: ✨ Feature, 🔨 Refactor

#134 fix : 홈 -> 검색 태그 선택으로 넘어가는 기능(엎해주세용)
  src/components/tag/SearchTag.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchList.tsx
  src/pages/search/handleSubmit.ts
  src/pages/search/options.ts
  src/recoil/barListAtom.ts
  src/recoil/cocktailListAtom.ts
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#137 fix : 홈 -> 검색으로 카테고리, 태그, 검색으로 넘어오는 경우 해당 값이 제대로 적용되지 않는 현상 수정
  src/components/search/Category.tsx
  src/libs/func/generator.ts
  src/libs/interface/interfaceCommon.tsx
  src/pages/search/Search.tsx
Labels: 🐞 BugFix

#136 add : signup 애니메이션 처리
  src/components/common/input/Input.tsx
  src/components/sign/SignUpForm.tsx
  src/libs/interface/interfaceCommon.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#138 fix: 로그인 관련 유효성 및 버그 수정
  src/components/sign/SignInForm.tsx
  src/pages/sign/PasswordReset.tsx
Labels: ✨ Feature, 🐞 BugFix

#140 design : height 조정
  src/App.tsx
  src/layouts/Layout.tsx
  src/layouts/adminLayout/AdminLayout.tsx
Labels: 🎨 HTML&CSS

#139 refactor, fix : 검색 페이지 useEffect 사용 줄임, 검색 결과 제대로 나오도록 수정
  src/libs/func/generator.ts
  src/pages/admin/bar/Popup.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchCategory.tsx
  src/pages/search/SearchForm.tsx
  src/pages/search/SearchList.tsx
  src/pages/search/SearchTag.tsx
  src/pages/search/Tag.tsx
  src/pages/search/listGenerator.ts
  src/pages/search/options.ts
  src/recoil/SearchAtom.ts
  src/recoil/adminAtom.ts
  src/recoil/barListAtom.ts
  src/recoil/cocktailListAtom.ts
  src/recoil/loadingAtom.ts
Labels: 🐞 BugFix, 🔨 Refactor

#141 feat: 비밀번호 보기 추가
  src/components/sign/SignInForm.tsx
  src/libs/constants/options/options.ts
  src/libs/interface/interfaceCommon.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#146 netlify 배포 development -> main
  package.json
  public/_redirects
  src/components/barDetail/BarInfomation.tsx
  src/components/common/cocktail/Cocktail.tsx
  src/components/common/input/Input.tsx
  src/components/home/HomeBanner.tsx
  src/components/search/Category.tsx
  src/components/sign/SignInForm.tsx
  src/components/sign/SignUpForm.tsx
  src/components/tag/Tag.tsx
  src/components/tag/TagList.tsx
  src/layouts/Layout.tsx
  src/layouts/adminLayout/AdminLayout.tsx
  src/libs/constants/options/options.ts
  src/libs/func/generator.ts
  src/libs/interface/interfaceCommon.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
  src/pages/home/Home.tsx
  src/pages/search/Search.tsx
  src/pages/search/SearchCategory.tsx
  src/pages/search/SearchForm.tsx
  src/pages/search/SearchList.tsx
  src/pages/search/SearchTag.tsx
  src/pages/search/Tag.tsx
  src/pages/search/handleSubmit.ts
  src/pages/search/listGenerator.ts
  src/pages/search/options.ts
  src/pages/sign/PasswordReset.tsx
  src/recoil/SearchAtom.ts
  src/recoil/adminAtom.ts
  src/recoil/loadingAtom.ts
Labels: 🌏 Deploy

#147 deploy test - 1
  src/assets/sample-img/sampleImg.png
  src/components/barDetail/BarInfomation.tsx
  src/components/common/text/text.tsx
  src/components/tag/Tag.tsx
  src/components/useCoupon/UseCouponPopup.tsx
  src/libs/utils/Bardetaildummy.ts
  src/pages/admin/bar/AdminBarDetail.tsx
  src/pages/barDetail/Bardetail.tsx
  src/pages/home/Home.tsx
  src/pages/myCoupon/UseCoupon.tsx
Labels: 🌏 Deploy

#148 refactor : 바정보관리, 팝업 input 값 변경시 리렌더링 되지 않도록 수정, 팝업 오류 수정
  src/components/admin/management/handleCocktailItem.ts
  src/libs/interface/interfaceCommon.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/ManageInfoOptions.ts
  src/pages/admin/bar/Popup.tsx
  src/pages/admin/bar/handler.ts
  src/pages/search/Tag.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#149 refactor : 바, 칵테일 요청 병렬처리, fix : 태그 선택된 상태에서 다른 태그 선택시 이전 선택태그 다시 나타나지 않는 현상 수정
  src/pages/search/SearchList.tsx
  src/pages/search/Tag.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#150 design 수정 및 api url 변경
  public/_redirects
  src/layouts/adminLayout/AdminLayout.tsx
  src/pages/admin/AdminSignIn.tsx
  src/setupProxy.js
Labels: ⚙ Setting, 🎨 HTML&CSS

#151 chore : backend url 변경
  public/_redirects
  src/setupProxy.js
Labels: ⚙ Setting, 📬 API

#154 bar detail navigate
  src/App.tsx
  src/components/common/input/Input.tsx
  src/libs/apis/user.ts
  src/libs/interface/interfaceAPI.ts
  src/pages/barDetail/Bardetail.tsx
  src/pages/myCoupon/UseCoupon.tsx
Labels: ✨ Feature

#155 fix : 검색결과 이미지 패스 변경
  src/pages/search/SearchForm.tsx
  src/pages/search/SearchList.tsx
  src/pages/subscribe/membership/Membership.tsx
  src/pages/subscribe/membership/handleMembership.ts
Labels: 🐞 BugFix

#156 refactor : 바관리페이지 컴포넌트분리, 리렌더최소화
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
  src/pages/admin/bar/RegistBarImageList.tsx
  src/pages/admin/bar/RegistCocktailList.tsx
  src/recoil/barManageAtom.ts
Labels: 🔨 Refactor

#161 배포 업데이트 - 2
  src/App.tsx
  src/components/common/input/Input.tsx
  src/components/sign/SignInForm.tsx
  src/components/stopSubscribe/StopMembership.tsx
  src/libs/apis/user.ts
  src/libs/interface/interfaceAPI.ts
  src/pages/Temporary.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
  src/pages/admin/bar/RegistBarImageList.tsx
  src/pages/admin/bar/RegistCocktailList.tsx
  src/pages/barDetail/Bardetail.tsx
  src/pages/myCoupon/UseCoupon.tsx
  src/pages/search/SearchForm.tsx
  src/pages/search/SearchList.tsx
  src/pages/subscribe/membership/Membership.tsx
  src/pages/subscribe/membership/handleMembership.ts
  src/recoil/barManageAtom.ts
Labels: 🌏 Deploy

#159 design : footer 수정
  src/layouts/footer/Footer.tsx
Labels: 🎨 HTML&CSS

#162 selectbox copy
  src/components/barDetail/BarInfomation.tsx
  src/components/barDetail/MainImage.tsx
  src/components/common/select/Select.tsx
  src/components/common/select/selectOptions.ts
  src/components/common/selectBox/BaseSelectBox.tsx
  src/components/common/selectBox/SelectBox.styled.ts
  src/components/common/selectBox/SelectBox.tsx
  src/components/common/selectBox/SelectItem.tsx
  src/components/common/selectBox/useSelectBox.ts
  src/components/home/HomeBanner.tsx
  src/components/tag/TagList.tsx
  src/components/useCoupon/ShowPopupButton.tsx
  src/components/useCoupon/UseCouponPopup.tsx
  src/libs/interface/interfaceCommon.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/ManageInfoOptions.ts
  src/pages/myCoupon/UseCoupon.tsx
Labels: ✨ Feature

#129 feat: 내 쿠폰함 기능 관련
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/ManualPaymentBtn.tsx
  src/components/coupon/NotCoupon.tsx
  src/components/coupon/UseHistory.tsx
  src/components/sign/SignInForm.tsx
  src/components/stopSubscribe/MembershipInfo.tsx
  src/components/stopSubscribe/PopupComplete.tsx
  src/components/stopSubscribe/PopupPromotion.tsx
  src/components/stopSubscribe/StopMembership.tsx
  src/libs/apis/baseUrl.ts
  src/libs/apis/myCoupon.ts
  src/libs/interface/interfaceMyCoupon.ts
  src/libs/interface/interfaceUserInfo.ts
  src/libs/utils/dateFormat.ts
  src/libs/utils/membershipPrice.ts
  src/libs/utils/priceFormat.ts
  src/pages/myCoupon/MyCoupon.tsx
  src/pages/stopSubscribe/StopSubscribe.tsx
Labels: ✨ Feature, 📬 API

#166 쿠폰 사용하기 기능
  src/assets/icon/icon_check_black.svg
  src/components/common/selectBox/BaseSelectBox.tsx
  src/components/home/ItemList.tsx
  src/components/useCoupon/ShowPopupButton.tsx
  src/components/useCoupon/UseCouponPopup.tsx
  src/components/useCoupon/UseCouponResultPopup.tsx
  src/libs/apis/barDetail.ts
  src/libs/apis/useCoupon.ts
  src/libs/constants/options/options.ts
  src/libs/interface/interfaceAPI.ts
  src/libs/interface/interfaceUseCoupon.ts
  src/pages/barDetail/Bardetail.tsx
  src/pages/myCoupon/UseCoupon.tsx
  src/pages/myCoupon/atom.ts
Labels: 🙋‍♂️ Question
