Repository Zanit-Development/Zanit_FE, pull requests merged in 2023-09, with the labels that each got.

#80 feat : gh-pages 배포 테스트
  package-lock.json
  package.json
  src/App.tsx
Labels: 🌏 Deploy

#81 feat : 로그인 기능 및 폼 데이터 인스턴스 추가
  src/libs/apis/axios.ts
  src/libs/apis/user.ts
  src/pages/sign/SignIn.tsx
Labels: ✨ Feature, 📬 API

#82 design : admin 바 관리 페이지
  src/components/common/input/Input.tsx
  src/pages/admin/bar/BarManagement.tsx
  src/pages/admin/bar/ManageInfo.tsx
Labels: 🎨 HTML&CSS

#83 design : 쿠폰 이용 내역, 정기 결제 해지
  src/App.tsx
  src/assets/icon/icon_arrow_promotion.svg
  src/assets/popup_promotion.svg
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/UseHistory.tsx
  src/components/modal/Modal.tsx
  src/components/stopSubscribe/MembershipInfo.tsx
  src/components/stopSubscribe/PopupComplete.tsx
  src/components/stopSubscribe/PopupPromotion.tsx
  src/components/stopSubscribe/StopMembership.tsx
  src/layouts/nav/Nav.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/pages/myCoupon/HowToUse.tsx
  src/pages/stopSubscribe/StopSubscribe.tsx
Labels: 🎨 HTML&CSS

#84 design : admin layout
  src/App.tsx
  src/layouts/adminLayout/AdminLayout.tsx
  src/layouts/nav/Nav.tsx
  src/pages/admin/bar/BarManagement.tsx
  src/pages/admin/bar/ManageOrder.tsx
Labels: 🎨 HTML&CSS

#86 design : 회원가입 성공 팝업 UI
  src/components/modal/UseSignPage/PopupPasswordFind.tsx
  src/components/modal/UseSignPage/PopupSignUpSuccess.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/pages/sign/SignUp.tsx
Labels: 🎨 HTML&CSS

#87 feat : 어드민 정보관리
  src/pages/admin/bar/BarManagement.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/ManageInfoOptions.ts
  src/pages/admin/bar/handler.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor

#89 design: 비밀번호 찾기 모달
  src/components/modal/UseSignPage/PopupPasswordFind.tsx
  src/components/modal/UseSignPage/PopupSignUpSuccess.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/pages/sign/PasswordFind.tsx
Labels: 🎨 HTML&CSS

#90 feat : 어드민 정보관리 페이지
  src/assets/admin_sample_img.svg
  src/assets/icon/icon_add_cocktail_button.svg
  src/assets/icon/icon_update_cocktail_button.svg
  src/components/admin/management/CocktailItem.tsx
  src/components/admin/management/cocktailItemOptions.ts
  src/components/admin/management/handleCocktailItem.ts
  src/pages/admin/bar/ManageInfo.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor, 🙋‍♂️ Question

#85 Feature/use coupon
  src/assets/icon/icon-checkmark-black.png
  src/components/bardetail/ImgContainer.tsx
  src/components/common/select-box/SelectBox.tsx
  src/components/common/select-box/SelectItem.tsx
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/ManualPaymentBtn.tsx
  src/components/modal/Modal.tsx
  src/components/useCoupon/ShowPopupButton.tsx
  src/components/useCoupon/UseCouponPopup.tsx
  src/libs/interface/interfaceUseCoupon.ts
  src/pages/myCoupon/UseCoupon.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 🙋‍♂️ Question

#88 refactor : bar_detail
  src/components/bardetail/Cocktail.tsx
  src/components/bardetail/ImageItem.tsx
  src/components/bardetail/ImgContainer.tsx
  src/components/bardetail/MainImage.tsx
  src/components/tag/Tag.tsx
  src/pages/barDetail/Bardetail.tsx
  src/recoil/mainImgAtom.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor

#92 admin bar information 마크업
  src/App.tsx
  src/components/admin/management/CocktailItem.tsx
  src/components/bardetail/BarInfomation.tsx
  src/components/common/cocktail/Cocktail.tsx
  src/components/tag/Tag.tsx
  src/components/tag/TagList.tsx
  src/layouts/adminLayout/AdminLayout.tsx
  src/libs/interface/interfaceCommon.tsx
  src/pages/admin/bar/AdminBarDetail.tsx
  src/pages/barDetail/Bardetail.tsx
  src/pages/search/Search.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#93 Temporary
  src/App.tsx
  src/components/bardetail/ImageItem.tsx
  src/components/bardetail/ImgContainer.tsx
  src/components/bardetail/MainImage.tsx
  src/components/home/ItemList.tsx
  src/layouts/adminLayout/AdminLayout.tsx
  src/pages/Temporary.tsx
  src/pages/subscribe/Subscribe.tsx
  src/pages/subscribe/SubscribeInfo.tsx
Labels: 🌏 Deploy, 🎨 HTML&CSS

#96 feat : 관리자 페이지 관련
  src/libs/interface/typeEvent.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/ManageInfoOptions.ts
  src/pages/admin/bar/handler.ts
Labels: ✨ Feature, 🔨 Refactor

#97 feat : 구독 종류 선택페이지
  src/App.tsx
  src/components/membership/MembershipType.tsx
  src/libs/interface/interfaceMembership.ts
  src/libs/interface/typeCommon.tsx
  src/pages/subscribe/Subscribe.tsx
  src/pages/subscribe/membership/Membership.tsx
  src/pages/subscribe/membership/handleMembership.ts
  src/pages/subscribe/membership/membershipOption.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor

#99 feat : 주문 관리
  src/libs/interface/interfaceManagement.ts
  src/pages/admin/bar/ManageOrder.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#101 fix : 스타일 조정
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/components/common/item/Item.tsx
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/ManualPaymentBtn.tsx
  src/components/coupon/NotCoupon.tsx
  src/components/coupon/UseHistory.tsx
  src/components/home/HomeBanner.tsx
  src/components/home/ItemList.tsx
  src/components/membership/MembershipType.tsx
  src/components/modal/Modal.tsx
  src/components/search/Category.tsx
  src/components/stopSubscribe/PopupComplete.tsx
  src/components/stopSubscribe/PopupPromotion.tsx
  src/components/stopSubscribe/StopMembership.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/nav/Nav.tsx
  src/libs/constants/options/options.ts
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/home/Home.tsx
  src/pages/myCoupon/HowToUse.tsx
  src/pages/search/Search.tsx
  src/pages/sign/PasswordFind.tsx
  src/pages/sign/SignIn.tsx
  src/pages/sign/SignUp.tsx
  src/pages/subscribe/membership/Membership.tsx
  src/style/GlobalStyle.tsx
Labels: 🎨 HTML&CSS

#102 rename : 폴더명 카멜케이스 변경
  src/App.tsx
  src/components/bardetail/BarInfomation.tsx
  src/components/common/selectBox/SelectBox.tsx
  src/components/common/selectBox/SelectItem.tsx
  src/libs/utils/dummy.txt
  src/pages/admin/bar/AdminBarDetail.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/barDetail/Bardetail.tsx
  src/pages/myCoupon/UseCoupon.tsx
  src/pages/sign/PasswordFind.tsx
  src/pages/sign/SignUp.tsx
Labels: 📃 Docs

#104 fix : 정기결제 해지 수정
  src/components/coupon/HasCoupon.tsx
  src/components/stopSubscribe/StopMembership.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
Labels: 🎨 HTML&CSS, 🐞 BugFix

#105 design : 비밀번호 재설정 완료, 어드민 로그인 페이지
  src/App.tsx
  src/assets/icon/icon_check_black.svg
  src/layouts/footer/Footer.tsx
  src/layouts/nav/Nav.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/regex/regex.ts
  src/libs/constants/values/outputValues.ts
  src/libs/constants/values/placeholder.ts
  src/pages/Temporary.tsx
  src/pages/admin/AdminSignIn.tsx
  src/pages/sign/PasswordReset.tsx
  src/pages/sign/PasswordResetOk.tsx
  src/pages/sign/SignIn.tsx
Labels: 🎨 HTML&CSS, 🙋‍♂️ Question

#112 feat : 검색기능
  src/components/common/item/Item.tsx
  src/libs/interface/interfaceCocktail.ts
  src/pages/search/Search.tsx
  src/pages/search/handleSubmit.ts
  src/pages/search/initBarList.ts
Labels: ✨ Feature

#113 feat : 검색 기능
  src/components/search/Category.tsx
  src/libs/interface/interfaceCommon.tsx
  src/libs/interface/interfaceSearch.ts
  src/pages/search/Search.tsx
  src/pages/search/handleSubmit.ts
Labels: ✨ Feature

#110 feat: 로그인 로직 변경
  src/components/modal/useSignPage/PopupSignUpSuccess.tsx
  src/components/sign/SignInForm.tsx
  src/components/sign/SignUpForm.tsx
  src/index.tsx
  src/layouts/nav/Nav.tsx
  src/libs/apis/axios.ts
  src/libs/apis/user.ts
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/pages/admin/AdminSignIn.tsx
  src/pages/sign/SignIn.tsx
  src/pages/sign/SignUp.tsx
  src/recoil/loginToken.ts
  src/setupProxy.js
Labels: ✨ Feature, 📬 API, 🔨 Refactor
