Repository Zanit-Development/Zanit_FE, pull requests merged in 2023-08, with the labels that each got.

#7 design : header, footer UI 추가
  src/App.tsx
  src/assets/custom.d.ts
  src/assets/icon/sns_Default.svg
  src/assets/icon/sns_Default_instar.svg
  src/layouts/Layout.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/header/Header.tsx
  src/libs/constants/routes/route.tsx
  src/pages/Home.tsx
  src/pages/search/Search.tsx
  src/recoil/atoms.ts
  src/style/GlobalStyle.tsx
  tsconfig.json
Labels: ⚙ Setting, 🎨 HTML&CSS

#9 feat: 공통 button, input 컴포넌트 추가
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/libs/apis/axios.ts
  src/libs/constants/routes/route.tsx
  src/libs/interface/interface.tsx
  src/libs/interface/type.tsx
  src/pages/search/Search.tsx
  src/recoil/atoms.ts
Labels: ✨ Feature

#10 chore : 모바일 화면 확인을 위한 메타 태그 추가
  public/index.html
  src/layouts/Layout.tsx
Labels: ⚙ Setting

#17 feat : 버튼 인터페이스 온클릭이벤트 추가
  src/libs/interface/interfaceCommon.tsx
Labels: ✨ Feature

#20 feat : 목록 아이템 컴포넌트, 검색 결과표시 기능, 스타일 수정사항
  src/assets/images.d.ts
  src/components/common/item/Item.tsx
  src/libs/interface/interfaceCommon.tsx
  src/libs/interface/typeCommon.tsx
  src/pages/search/Search.tsx
  src/style/GlobalStyle.tsx
  tsconfig.json
Labels: ✨ Feature, 🎨 HTML&CSS

#22 design : 레이아웃 변경 작업
  public/index.html
  src/App.tsx
  src/assets/font.css
  src/assets/logo.svg
  src/layouts/Layout.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/nav/Nav.tsx
  src/pages/subscribe/Subscribe.tsx
  src/style/GlobalStyle.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#28 design : 회원가입 페이지 UI
  src/assets/icon/check.svg
  src/libs/interface/interfaceCommon.tsx
  src/libs/interface/typeCommon.tsx
  src/pages/sign/SignIn.tsx
  src/pages/sign/SignUp.tsx
Labels: 🎨 HTML&CSS

#31 feat : enum 수정/추가, 파일분리 예시
  src/components/common/input/setPlaceholder.ts
  src/libs/constants/messages/placeholder.ts
  src/libs/constants/values/outputValues.ts
  src/libs/constants/values/placeholder.ts
  src/libs/interface/interfaceCommon.tsx
  src/libs/interface/typeCommon.tsx
  src/pages/sign/SignIn.tsx
  src/pages/sign/SignUp.tsx
  src/pages/sign/signOptions.ts
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#34 chore : options 이동 및 적용
  src/libs/constants/options/options.ts
  src/pages/Home.tsx
  src/pages/sign/SignIn.tsx
  src/pages/sign/SignUp.tsx
Labels: 🔨 Refactor

#35 design : 내 쿠폰함 UI
  src/App.tsx
  src/assets/coupon_bg.png
  src/assets/coupon_bg.svg
  src/assets/icon/icon_arrow_right.svg
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/NotCoupon.tsx
  src/layouts/nav/Nav.tsx
  src/libs/constants/options/options.ts
  src/pages/myCoupon/HowToUse.tsx
  src/pages/myCoupon/MyCoupon.tsx
Labels: 🎨 HTML&CSS

#36 feat : 구독 페이지
  src/assets/icon/icon_subtract.svg
  src/assets/subscribe.svg
  src/components/common/button/Button.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/libs/interface/interfaceSubscribe.tsx
  src/pages/subscribe/Subscribe.tsx
  src/pages/subscribe/SubscribeInfo.tsx
  src/pages/subscribe/subscribeOption.ts
Labels: ✨ Feature, 🎨 HTML&CSS

#37 fix : 쿠폰 페이지 버튼 옵션 변경
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/NotCoupon.tsx
  src/libs/constants/options/options.ts
  src/pages/myCoupon/HowToUse.tsx
Labels: 🐞 BugFix

#38 feat : 구독 팝업, 공용 경고(주의) 컴포넌트 추가
  src/components/common/alert/Alert.tsx
  src/libs/constants/options/options.ts
  src/pages/subscribe/Popup.tsx
  src/pages/subscribe/Subscribe.tsx
  src/pages/subscribe/SubscribeInfo.tsx
  src/pages/subscribe/subscribeOption.ts
Labels: ✨ Feature, 🎨 HTML&CSS

#39 style : 불필요 백틱 삭제, 레이아웃 적용
  src/components/common/alert/Alert.tsx
  src/pages/subscribe/Subscribe.tsx
Labels: 🎨 HTML&CSS, 📃 Docs

#40 docs : React.FC 제거 및 export default 변경
  src/App.tsx
  src/components/common/button/Button.tsx
  src/components/common/input/CheckboxTag.tsx
  src/components/common/input/CheckboxTerms.tsx
  src/components/common/input/Input.tsx
  src/components/common/item/Item.tsx
  src/components/common/logo/Logo.tsx
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/NotCoupon.tsx
  src/components/error/Page404.tsx
  src/components/home/HomeBanner.tsx
  src/components/home/ItemList.tsx
  src/components/nav/Nav.tsx
  src/components/search/Category.tsx
  src/components/tag/Tag.tsx
  src/components/tag/TagList.tsx
  src/components/terms/Term.tsx
  src/layouts/Layout.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/header/Header.tsx
  src/layouts/nav/Nav.tsx
  src/pages/Home.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/home/Home.tsx
  src/pages/myCoupon/HowToUse.tsx
  src/pages/myCoupon/MyCoupon.tsx
  src/pages/search/Search.tsx
  src/pages/sign/SignIn.tsx
  src/pages/sign/SignUp.tsx
  src/pages/subscribe/Popup.tsx
  src/pages/subscribe/Subscribe.tsx
Labels: 📃 Docs

#41 design : 레이아웃 디자인 변경 수정
  public/index.html
  src/assets/icon/icon_sns_cafe.svg
  src/assets/icon/icon_sns_instar.svg
  src/assets/icon/icon_sns_kakao.svg
  src/layouts/Layout.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/nav/Nav.tsx
Labels: 🎨 HTML&CSS

#43 #42 feat : 바 상세페이지
  src/App.tsx
  src/components/bardetail/BardetailTag.tsx
  src/components/bardetail/Cocktail.tsx
  src/components/tag/Tag.tsx
  src/libs/interface/interfaceBarDetail.ts
  src/libs/utils/Bardetaildummy.ts
  src/libs/utils/Homedummy.ts
  src/pages/bar_detail/Bardetail.tsx
  src/pages/home/Home.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#44 #42 refactor : 태그 컴포넌트로 변경
  src/components/bardetail/BardetailTag.tsx
  src/components/bardetail/Cocktail.tsx
  src/libs/utils/Homedummy.ts
  src/pages/bar_detail/Bardetail.tsx
Labels: 🔨 Refactor

#47 feat : 모달 기능 추가, 버튼 기능 변경
  src/assets/icon/icon_close.svg
  src/components/common/button/Button.tsx
  src/components/modal/Modal.tsx
  src/components/modal/dummy.txt
  src/libs/interface/interfaceCommon.tsx
  src/libs/interface/typeCommon.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#48 fix : 버튼 옵션 변경
  public/apple-touch-icon.png
  public/favicon.svg
  public/index.html
  src/components/error/Page404.tsx
  src/components/home/HomeBanner.tsx
  src/layouts/nav/Nav.tsx
  src/libs/constants/options/options.ts
  src/pages/bar_detail/Bardetail.tsx
Labels: 🐞 BugFix

#49 #21 refactor : 컴포넌트 수정
  src/components/home/HomeBanner.tsx
  src/components/home/ItemList.tsx
  src/components/home/index.ts
  src/components/tag/TagList.tsx
  src/libs/constants/options/options.ts
  src/libs/utils/Homedummy.ts
  src/pages/home/Home.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#50 design : nav, footer 수정
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/assets/icon/icon_sns_cafe.svg
  src/assets/icon/icon_sns_instar.svg
  src/assets/icon/icon_sns_kakao.svg
  src/assets/logo_footer.svg
  src/index.tsx
  src/layouts/footer/Footer.tsx
  src/layouts/nav/Nav.tsx
  src/recoil/atoms.ts
  src/recoil/loginToken.ts
Labels: 🎨 HTML&CSS

#52 fix : 인터페이스 옵션 카멜케이스 소문자로 변경
  src/libs/constants/options/options.ts
  src/libs/interface/interfaceBarDetail.ts
  src/libs/interface/interfaceCommon.tsx
  src/pages/search/Search.tsx
Labels: 🐞 BugFix

#53 fix : 모달 카멜케이스 소문자로 변경
  src/components/modal/Modal.tsx
Labels: 🐞 BugFix

#54 refactor : 카멜케이스 수정, 인풋 인터페이스 옵션 변경 및 스타일 제네릭 옵션 추가
  src/components/common/input/Input.tsx
  src/components/common/input/inputOptions.ts
  src/components/tag/Tag.tsx
  src/components/tag/TagList.tsx
  src/libs/interface/interfaceCommon.tsx
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#56 desgin : 페이지 별 nav 버튼 활성화 연결
  src/layouts/nav/Nav.tsx
Labels: 🎨 HTML&CSS

#58 design : 구독페이지 변경사항 적용
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/pages/subscribe/Subscribe.tsx
  src/pages/subscribe/SubscribeInfo.tsx
  src/pages/subscribe/subscribeOption.ts
Labels: 🎨 HTML&CSS

#59 feat : 구독 할인쿠폰 컴포넌트 추가
  src/assets/coupon_bg2.svg
  src/assets/reborn_bg.svg
  src/pages/subscribe/DiscountCoupon.tsx
  src/pages/subscribe/Subscribe.tsx
  src/pages/subscribe/subscribeOption.ts
Labels: ✨ Feature

#60 markup - bar detail
  src/App.tsx
  src/assets/icon/icon_cocktail.png
  src/assets/sample-img/bar1.jpg
  src/assets/sample-img/bar1.png
  src/assets/sample-img/bar2.jpg
  src/assets/sample-img/bar2.png
  src/assets/sample-img/bar3.jpg
  src/assets/sample-img/bar3.png
  src/assets/sample-img/bar4.jpg
  src/assets/throughArrow.svg
  src/components/bardetail/Cocktail.tsx
  src/components/bardetail/ImageItem.tsx
  src/components/bardetail/ImgContainer.tsx
  src/index.tsx
  src/libs/interface/interfaceBarDetail.ts
  src/libs/interface/typeEvent.tsx
  src/libs/utils/Bardetaildummy.ts
  src/pages/barDetail/Bardetail.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#61 (#21) fix : 오류 수정
  src/components/home/HomeBanner.tsx
  src/libs/utils/Homedummy.ts
  src/pages/home/Home.tsx
Labels: 🐞 BugFix

#63 fix : 카멜케이스 소문자로 수정, 태그 라디오버튼 수정
  src/components/common/item/Item.tsx
  src/components/tag/Tag.tsx
  src/pages/search/Search.tsx
Labels: 🐞 BugFix

#64 Fix : 페이지 에러 해결
  src/components/common/input/setPlaceholder.ts
  src/components/coupon/AutoPaymentCoupon.tsx
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/ManualPaymentCoupon.tsx
  src/components/error/Page404.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/placeholder.ts
  src/pages/sign/SignUp.tsx
  src/pages/subscribe/subscribeOption.ts
Labels: 🐞 BugFix

#67 design : header 고정, main 스크롤바
  src/layouts/Layout.tsx
  src/layouts/header/Header.tsx
  src/layouts/nav/Nav.tsx
  src/pages/subscribe/Subscribe.tsx
Labels: 🎨 HTML&CSS

#66 design : 자동, 수동 결제에 따른 쿠폰함 UI
  src/assets/coupon_bg_used.svg
  src/assets/icon/icon_sad_face.svg
  src/assets/icon/icon_used_coupon.svg
  src/assets/speech_bubble.svg
  src/components/coupon/AutoPaymentCoupon.tsx
  src/components/coupon/HasCoupon.tsx
  src/components/coupon/ManualPaymentBtn.tsx
  src/components/coupon/ManualPaymentCoupon.tsx
  src/components/coupon/NotCoupon.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
Labels: 🎨 HTML&CSS

#68 design : 상단여백 길이조절
  src/pages/subscribe/Subscribe.tsx
Labels: 🎨 HTML&CSS

#69 fix : ScrollMain css 수정
  src/layouts/Layout.tsx
Labels: 🎨 HTML&CSS, 🐞 BugFix

#70 design : 모달 컴포넌트 작업
  public/index.html
  src/App.tsx
  src/components/common/text/index.ts
  src/components/common/text/text.tsx
  src/components/modal/Modal.tsx
  src/libs/interface/interfaceCommon.tsx
  src/pages/barDetail/Bardetail.tsx
  src/pages/myCoupon/UseCoupon.tsx
Labels: 🎨 HTML&CSS, 🔨 Refactor

#76 feat : 어드민 바 관리 페이지
  src/components/common/input/CheckboxTag.tsx
  src/components/common/input/CheckboxTerms.tsx
  src/components/common/select/Select.tsx
  src/pages/admin/bar/BarManagement.tsx
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/ManageInfoOptions.ts
  src/pages/admin/bar/ManageOrder.tsx
Labels: 🎨 HTML&CSS
