Repository Zanit-Development/Zanit_FE, pull requests merged in 2023-11, with the labels that each got.

#169 feat: 비밀번호 찾기, 재설정 코드 수정
  src/components/sign/SignInForm.tsx
  src/libs/apis/user.ts
  src/pages/sign/PasswordFind.tsx
  src/pages/sign/PasswordReset.tsx
Labels: 📬 API

#171 feat : 칵테일 표시기능 속성값에 적용
  src/components/admin/management/CocktailItem.tsx
  src/components/admin/management/handleCocktailItem.ts
  src/libs/interface/interfaceCocktail.ts
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
  src/pages/admin/bar/RegistCocktailList.tsx
Labels: ✨ Feature, 🔨 Refactor

#172 feat : 바,칵테일 등록 api 연결
  src/libs/apis/axios.ts
  src/libs/interface/interfaceCocktail.ts
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/Popup.tsx
Labels: ✨ Feature, 🔨 Refactor

#173 바 상세페이지 및 홈화면
  src/components/barDetail/BarInfomation.tsx
  src/components/common/selectBox/SelectBox.styled.ts
  src/components/common/text/text.tsx
  src/components/home/ItemList.tsx
  src/components/useCoupon/ShowPopupButton.tsx
  src/libs/apis/axios.ts
  src/libs/apis/barDetail.ts
  src/libs/interface/interfaceAPI.ts
  src/libs/interface/interfaceBarDetail.ts
  src/libs/interface/interfaceUseCoupon.ts
  src/libs/utils/Bardetaildummy.ts
  src/pages/admin/bar/AdminBarDetail.tsx
  src/pages/admin/bar/getAdminBar.ts
  src/setupProxy.js
Labels: ✨ Feature, 🎨 HTML&CSS

#180 feat : 칵테일 금액입력 기능 추가, 스타일 적용
  src/pages/admin/bar/Popup.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#185 Feat : X멤버십 구독자인 경우 '이미구독자'팝업 되는 기능, 팝업, 구독/연장 분기처리
  src/pages/subscribe/membership/Membership.tsx
  src/pages/subscribe/membership/Popup.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#184 feat : bar location detail 추가
  src/components/barDetail/BarInfomation.tsx
  src/components/home/ItemList.tsx
  src/libs/apis/barDetail.ts
  src/libs/interface/interfaceAPI.ts
  src/libs/interface/interfaceBarDetail.ts
  src/libs/utils/Bardetaildummy.ts
  src/pages/admin/bar/AdminBarDetail.tsx
  src/pages/admin/bar/getAdminBar.ts
Labels: ✨ Feature

#186 feat : 관리자 바,칵테일 관련 / 구독 여부 관련 버튼값 등 / refactor : formdata값 직접 넣는 코드 제거 -> name값 통일후 form 자체 입력되도록 수정
  src/components/admin/management/CocktailItem.tsx
  src/libs/constants/options/options.ts
  src/libs/constants/values/outputValues.ts
  src/libs/interface/interfaceCocktail.ts
  src/pages/admin/bar/ManageInfo.tsx
  src/pages/admin/bar/ManageInfoOptions.ts
  src/pages/admin/bar/Popup.tsx
  src/pages/admin/bar/RegistCocktailList.tsx
  src/pages/admin/bar/sample.json
  src/recoil/barManageAtom.ts
Labels: ✨ Feature, 🔨 Refactor

#189 fix : 오타 수정
  package-lock.json
  package.json
  src/pages/admin/bar/AdminBarDetail.tsx
Labels: 🐞 BugFix
